<?php

namespace Database\Seeders;

use App\Models\DatasetSayuran;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DatasetSayuranSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dataset_sayurans = array(
            array('id' => '1', 'nama_sayuran' => 'Bayam', 'manfaat' => 'Mencegah anemia, meningkatkan produksi sel darah merah, mendukung kesehatan tulang, memperbaiki daya tahan tubuh, mencegah rambut rontok', 'nutrisi' => 'Zat besi, Vitamin A, C, K, Folat', 'status' => 'Buruk , Baik', 'gejala' => 'Anemia, rambut rontok', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '2', 'nama_sayuran' => 'Kangkung', 'manfaat' => 'Mencegah anemia, menjaga kesehatan mata & kulit, meningkatkan daya tahan tubuh', 'nutrisi' => 'Zat besi, Vitamin C, Kalsium', 'status' => 'Buruk , Baik', 'gejala' => 'Anemia, sembelit', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '3', 'nama_sayuran' => 'Wortel', 'manfaat' => 'Menjaga kesehatan mata, melindungi kulit dari radikal bebas, memperkuat sistem imun, melancarkan pencernaan', 'nutrisi' => 'Beta-karoten, Serat, Vitamin C', 'status' => 'Buruk , Baik', 'gejala' => 'Kulit kering, rambut rontok, sembelit', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '4', 'nama_sayuran' => 'Brokoli', 'manfaat' => 'Mencegah anemia, mnurunkan risiko kanker, meningkatkan imun, menjaga kesehatan jantung', 'nutrisi' => 'Zat besi, Serat, Vitamin C, Folat', 'status' => 'Buruk , Baik', 'gejala' => 'Anemia, kulit kering', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '5', 'nama_sayuran' => 'Labu Kuning', 'manfaat' => 'Menjaga kesehatan mata, menurunkan kolesterol, memperkuat imun, melancarkan pencernaan', 'nutrisi' => 'Vitamin A, Serat, Kalium', 'status' => 'Buruk , Baik', 'gejala' => 'Sembelit, anemia', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '6', 'nama_sayuran' => 'Kacang Panjang', 'manfaat' => 'Mendukung pertumbuhan, menurunkan tekanan darah, menjaga kesehatan kulit, meningkatkan metabolisme', 'nutrisi' => 'Protein nabati, Vitamin C, Serat', 'status' => 'Baik', 'gejala' => 'Anemia, sembelit', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '7', 'nama_sayuran' => 'Buncis', 'manfaat' => 'Menurunkan kadar gula darah, melancarkan pencernaan, mencegah anemia, meningkatkan energi', 'nutrisi' => 'Protein nabati, Zat besi, Folat', 'status' => 'Baik , Buruk', 'gejala' => 'Anemia, obesitas', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '8', 'nama_sayuran' => 'Timun', 'manfaat' => 'Menjaga hidrasi tubuh, menurunkan tekanan darah, melancarkan pencernaan, menyehatkan kulit', 'nutrisi' => 'Vitamin K, Rendah kalori', 'status' => 'Baik', 'gejala' => 'Kulit kering', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '9', 'nama_sayuran' => 'Daun Singkong', 'manfaat' => 'Mencegah anemia, memperkuat tulang, mempercepat penyembuhan luka, melancarkan pencernaan', 'nutrisi' => 'Zat besi, Vitamin B6, Serat, Kalsium', 'status' => 'Buruk , Baik', 'gejala' => 'Anemia, sembelit', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '10', 'nama_sayuran' => 'Selada', 'manfaat' => 'Membantu diet, melancarkan pencernaan, menjaga kesehatan tulang, menurunkan risiko penyakit jantung', 'nutrisi' => 'Serat, Vitamin K, Folat', 'status' => 'Baik', 'gejala' => 'Obesitas', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '11', 'nama_sayuran' => 'Kubis/Kol', 'manfaat' => 'Detoksifikasi tubuh, melawan radikal bebas, mencegah kanker, melancarkan pencernaan', 'nutrisi' => 'Vitamin C, Serat, Glukosinolat', 'status' => 'Buruk , Baik', 'gejala' => 'Obesitas, anemia', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '12', 'nama_sayuran' => 'Sawi Hijau', 'manfaat' => 'Menambah energi, menjaga kesehatan tulang, mencegah anemia, memperkuat daya tahan tubuh', 'nutrisi' => 'Vitamin C, Zat besi, Serat', 'status' => 'Buruk , Baik', 'gejala' => 'Anemia, sembelit', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '13', 'nama_sayuran' => 'Terong', 'manfaat' => 'Menurunkan kadar kolesterol, menjaga kesehatan jantung, menurunkan kadar gula', 'nutrisi' => 'Serat, Antioksidan, Vitamin B1', 'status' => 'Buruk , Baik', 'gejala' => 'Anemia, obesitas', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '14', 'nama_sayuran' => 'Daun Kelor', 'manfaat' => 'Mencegah anemia, meningkatkan daya tahan tubuh, memperkuat tulang, mengatasi malnutrisi', 'nutrisi' => 'Zat besi, Kalsium, Vitamin A', 'status' => 'Buruk , Baik', 'gejala' => 'Anemia, rambut rontok', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '15', 'nama_sayuran' => 'Kentang', 'manfaat' => 'Meningkatkan sumber energi, mengontrol tekanan darah, meningkatkan daya tahan tubuh, memperbaiki metabolisme', 'nutrisi' => 'Karbohidrat, Kalium, Vitamin C', 'status' => 'Buruk , Baik', 'gejala' => 'Anemia, obesitas', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '16', 'nama_sayuran' => 'Kembang Kol', 'manfaat' => 'Meningkatkan imun, menurunkan risiko kanker, melancarkan pencernaan, menurunkan kolesterol', 'nutrisi' => 'Vitamin C, Folat, Serat', 'status' => 'Baik , Buruk', 'gejala' => 'Anemia, sembelit', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '17', 'nama_sayuran' => 'Pakcoy', 'manfaat' => 'Meningkatkan imunitas, memperkuat tulang, menjaga kesehatan mata & kulit, mencegah anemia', 'nutrisi' => 'Vitamin A, C, K, Kalsium', 'status' => 'Baik , Buruk', 'gejala' => 'Anemia, kulit kering', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '18', 'nama_sayuran' => 'Labu Siam', 'manfaat' => 'Menurunkan tekanan darah, menjaga kesehatan pencernaan, mendukung fungsi ginjal', 'nutrisi' => 'Serat, Vitamin B6, Folat, Kalium', 'status' => 'Buruk , Baik', 'gejala' => 'Anemia, sembelit', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '19', 'nama_sayuran' => 'Tomat', 'manfaat' => 'Menurunkan risiko kanker, menyehatkan jantung, menjaga kesehatan kulit & mata', 'nutrisi' => 'Vitamin C, Likopen, Beta-karoten', 'status' => 'Buruk , Baik', 'gejala' => 'Anemia, kulit kering', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '20', 'nama_sayuran' => 'Jagung Muda', 'manfaat' => 'Mendukung kesehatan pencernaan, meningkatkan sumber energi, menjaga kesehatan saraf', 'nutrisi' => 'Serat, Folat, Karbohidrat, Vitamin B', 'status' => 'Baik', 'gejala' => 'Anemia, sembelit', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '21', 'nama_sayuran' => 'Tauge', 'manfaat' => 'Meningkatkan kesuburan, memperkuat imun, melancarkan pencernaan, mencegah anemia', 'nutrisi' => 'Folat, Vitamin C, K, Zat besi, Protein', 'status' => 'Buruk , Baik', 'gejala' => 'Anemia, sembelit', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '22', 'nama_sayuran' => 'Sawi Putih', 'manfaat' => 'Membantu metabolisme tubuh, memperkuat tulang, melancarkan pencernaan, mencegah anemia', 'nutrisi' => 'Fosfor, Vitamin C, Folat, Kalsium', 'status' => 'Buruk , Baik', 'gejala' => 'Anemia, sembelit', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '23', 'nama_sayuran' => 'Nangka Muda', 'manfaat' => 'Menurunkan tekanan darah, mendukung pembentukan sel darah merah, meningkatkan energi', 'nutrisi' => 'Kalium, Fosfor, Vitamin A, B1, C', 'status' => 'Buruk , Baik', 'gejala' => 'Anemia, sembelit', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '24', 'nama_sayuran' => 'Pepaya Muda', 'manfaat' => 'Melancarkan pencernaan, menurunkan kadar gula, memperbaiki kesehatan kulit, meningkatkan imun', 'nutrisi' => 'Vitamin A, C, E, Kalium, Enzim Papain', 'status' => 'Buruk , Baik', 'gejala' => 'Anemia, sembelit', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50'),
            array('id' => '25', 'nama_sayuran' => 'Jamur Shitake', 'manfaat' => 'Meningkatkan sistem imun, menurunkan kolesterol, menjaga kesehatan jantung, mendukung kesehatan tulang, mencegah anemia', 'nutrisi' => 'Protein nabati, Vitamin B, Vitamin D, Selenium, Zat besi, Serat', 'status' => 'Buruk , Baik', 'gejala' => 'Anemia', 'created_at' => '2025-08-31 10:54:50', 'updated_at' => '2025-08-31 10:54:50')
        );
        DatasetSayuran::insert($dataset_sayurans);
    }
}
